import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gradient-to-b from-gray-50 via-white to-gray-100 dark:from-gray-900 dark:via-gray-900 dark:to-black">
        <div className="w-full bg-white/60 dark:bg-black/40 backdrop-blur sticky top-0 z-10">
          <header className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
            <a href="/" className="text-xl font-bold tracking-tight">News Portal</a>
            <nav className="space-x-4 text-sm">
              <a href="/" className="text-gray-700 dark:text-gray-200 hover:underline">Home</a>
              <a href="/trending" className="text-gray-700 dark:text-gray-200 hover:underline">Trending</a>
              <a href="/live-metrics" className="text-gray-700 dark:text-gray-200 hover:underline">Live</a>
              <a href="/category/Tech" className="text-gray-700 dark:text-gray-200 hover:underline">Categories</a>
            </nav>
          </header>
        </div>

        <main className="flex-grow container max-w-5xl mx-auto px-6 py-8">{children}</main>
      </body>
    </html>
  );
}
